/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package geotab_1;

import org.junit.Test;

public class MainTest {
    @Test public void testmainMethod() {
    	//Main classUnderTest = new Main();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.getClass());
    }
}
